#!/usr/bin/env perl

#A  Greg Gamble ... based in part on Frank Lübeck's packpack
## 
##  Usage: make_zoo
##
##  Uses perl and zoo to create just the <pname>-<version>.zoo
##  and copies the README to README.<pname> (both are placed in
##  the pkg directory).
##

#set values of <pname> and <version>
$pname = "example";
$version = "1.5";

#if <version> is in file VERSION uncomment and capture it this way
#$version = `cat VERSION`;
#chomp $version;

#package documentation prefix
$pdoc = $pname . "doc";

#remove files created during installation
system( "make clean" );

#remove old .zoo files
system( "rm -f ../$pname*-$version.zoo" );

#copy README in pkg directory 
system( "cp -f README ../README.$pname" );

### Create new .zoo files in pkg directory ##################################
chdir "..";

# substrings (mainly suffixes) that determine files we want to exclude
$prune = "[._]cvs|[.]bbl|[.]aux|[.]toc|[.][ib]lg|[.]log|[.]lab|[.]ind|[.]idx".
#         "|zoo|make_".         # uncomment to exclude make_doc, make_zoo etc.
         "|[.]sw[op]|[.-]bak|~|[.][#]";

# documentation files are in doc/ and htm/ directories
$doc = "doc\/|htm\/";

# find command used
$find = "find $pname -name CVS -prune -o -print | egrep -v '$prune' ";

# Create the main .zoo file
system( "$find | zoo ahI $pname-$version.zoo" );

system( "$find | egrep '$doc'" );
# Create the doc .zoo file
system( "$find | egrep '$doc' | zoo ahI $pdoc-$version.zoo" );

@files = `find $pname -name CVS -prune -o -print | egrep -v '$prune'`;
# Mark some files as text files
for $file ( @files ) {
  chomp $file;
  if ($file =~ /[.](txt|ps|g(|[id])|htm(|l)|[ch]|xml|tex|bib|six|tst|mst)$/ ||
      $file =~ /(VERSION|README|INSTALL|Makefile|configure|make_)/) {
    if ($file =~ /($doc)/) {
      system( "(echo '!TEXT!'; echo '/END') | zoo c $pdoc-$version.zoo $file" );
    }
    system( "(echo '!TEXT!'; echo '/END') | zoo c $pname-$version.zoo $file" );
  }
}
