name: Example
version: "4.4.0"
license: "GPL-2.0-or-later"
date: 2024-11-20
description: |
    Example/Template of a GAP Package

authors:
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel
    - name: Greg Gamble
      url: http://www.math.rwth-aachen.de/~Greg.Gamble
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/

maintainers:
    - name: Greg Gamble
      url: http://www.math.rwth-aachen.de/~Greg.Gamble
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/

GAP: "4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/example
readme: README.md
packageinfo: https://gap-packages.github.io/example/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/example/releases/download/v4.4.0/Example-4.4.0.tar.gz

abstract: |
    The <span class="pkgname">Example</span> package, as its name suggests,    is an example of how to create a <span class="pkgname">GAP</span>    package. It has little functionality except for being a package.

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    package example, package template.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>NGK20</span>]   <b class='BibAuthor'>Nickel, W., Gamble, G. and Konovalov, O.</b>,
     <i class='BibTitle'>Example, Example/Template of a GAP Package,
             Version 4.4.0</i>
     (<span class='BibYear'>1-20</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/example">https://gap-packages.github.io/example</a></span>.
    </p>
    

bibtex: |
    @misc{ Example,
      author =           {Nickel, W. and Gamble, G. and Konovalov, O.},
      title =            {{Example}, {Example/Template of a GAP Package}, {V}ersion 4.4.0},
      month =            {4\texttt{\symbol{45}}},
      year =             {1\texttt{\symbol{45}}20},
      note =             {GAP package},
      howpublished =     {\href                                             {https://gap-packages.github.io/example}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{example}}},
      keywords =         {package example; package template},
      printedkey =       {NGK20}
    }

